apiVersion: linkerd.io/v1alpha1
kind: ServiceProfile
metadata:
  name: customers-service.default.svc.cluster.local
  namespace: default
spec:
  routes:
    - name: "/actuator/health"
      condition:
        method: GET
      isRetryable: true
      timeout: "1s"

    - name: "/actuator/conditions"
      condition:
        method: GET
      isRetryable: true
      timeout: "1s"

    - name: "/actuator/metrics"
      condition:
        method: GET
      isRetryable: true
      timeout: "1s"
