apiVersion: v1
kind: Service
metadata:
  name: customers-service
  namespace: default
  labels:
    app: customers-service
spec:
  type: ClusterIP  
  selector:
    app: customers-service
  ports:
    - name: http
      port: 80          # Puertos a exponer
      protocol: TCP
      targetPort: 8081   # Puerto en el contenedor al que deseas redirigir el tráfico
