apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: kube-system
  labels:
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/part-of: argocd
data:
  service.email: |
    host: smtp.sendgrid.net
    port: 587
    from: dmh1802@gmail.com
    username: Moltica
    password: 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

  triggers.on-sync-succeeded: |
    - name: on-sync-succeeded
      condition: app.status.operationState.phase == 'Succeeded'
      template: app-sync-succeeded

  triggers.on-sync-failed: |
    - name: on-sync-failed
      condition: app.status.operationState.phase == 'Failed'
      template: app-sync-failed

  templates.app-sync-succeeded: |
    email:
      subject: Application {{.app.metadata.name}} synchronized successfully
      body: |
        Application {{.app.metadata.name}} has been successfully synchronized.
        View it at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}

  templates.app-sync-failed: |
    email:
      subject: Application {{.app.metadata.name}} synchronization failed
      body: |
        Application {{.app.metadata.name}} has failed to synchronize.
        View it at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}
