apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: grafana-server-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: grafana-server
  pollingInterval: 30
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 2  # Limita el escalado ya que normalmente Grafana no requiere muchas réplicas
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "20"
