apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: prometheus-server-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: prometheus-server
  pollingInterval: 30
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 2
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "20"
