apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: vets-service-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: vets-service
  pollingInterval: 30
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "20"
