apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
      annotations:
        linkerd.io/inject: enabled  # Anotación para la inyección de Linkerd
        config.linkerd.io/proxy-cpu-request: "50m"    # Solicitud mínima de CPU para linkerd-proxy
        config.linkerd.io/proxy-cpu-limit: "100m"     # Límite de CPU para linkerd-proxy
        config.linkerd.io/proxy-memory-request: "32Mi" # Solicitud mínima de memoria para linkerd-proxy
        config.linkerd.io/proxy-memory-limit: "64Mi"   # Límite de memoria para linkerd-proxy
    spec:
      containers:
        - name: config-server
          image: petdistriacr.azurecr.io/spring-petclinic-config-server:latest
          ports:
            - containerPort: 8888
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 15
            periodSeconds: 5
      imagePullSecrets:
        - name: acr-auth
      restartPolicy: Always
