name: Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Fetch Image Name from Temp Branch
        run: |
          BRANCH_NAME="temp/image-info-${{ github.event.before }}"
          git fetch origin $BRANCH_NAME:$BRANCH_NAME || exit 0
          git checkout $BRANCH_NAME || exit 0
          IMAGE_NAME=$(cat spring-petclinic-vets-service/image_name.txt)
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name petdistriACR

      - name: Deploy Docker Image
        run: |
          ORIGINAL_IMAGE_NAME=$IMAGE_NAME
          NEW_IMAGE_NAME="petdistriacr.azurecr.io/spring-petclinic-vets-service:deploy-${{ github.run_number }}"

          echo "Original image: $ORIGINAL_IMAGE_NAME"
          echo "New image: $NEW_IMAGE_NAME"

          # Pull, retag, and push the image
          docker pull $ORIGINAL_IMAGE_NAME
          docker tag $ORIGINAL_IMAGE_NAME $NEW_IMAGE_NAME
          docker push $NEW_IMAGE_NAME

      - name: Delete Temporary Branch
        if: always()
        run: |
          BRANCH_NAME="temp/image-info-${{ github.event.before }}"
          git push origin --delete $BRANCH_NAME || echo "Branch already deleted"
