name: Deploy Docker Image to ACR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout el código
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Loguearse en Azure (asegúrate de tener las credenciales configuradas en los secretos)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Autenticarse en el ACR
      - name: Docker Login to ACR
        run: |
          az acr login --name petdistriACR

      # 4. Renombrar la imagen y subirla al ACR
      - name: Tag and Push Docker Image
        run: |
          ORIGINAL_IMAGE_NAME="petdistriacr.azurecr.io/spring-petclinic-vets-service:pr-${{ github.run_id }}"
          NEW_IMAGE_NAME="petdistriacr.azurecr.io/spring-petclinic-vets-service:deploy-${{ github.run_number }}"
          
          echo "Original image: $ORIGINAL_IMAGE_NAME"
          echo "New image: $NEW_IMAGE_NAME"
          
          # Renombrar la imagen
          docker tag $ORIGINAL_IMAGE_NAME $NEW_IMAGE_NAME
          
          # Subir la nueva imagen al ACR
          docker push $NEW_IMAGE_NAME

      # 5. Post Deploy Output
      - name: Post Deploy Output
        run: |
          echo "Docker image successfully pushed to ACR with tag: deploy-${{ github.run_number }}"
