name: Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name petdistriACR

      - name: Download Image Name Artifact
        uses: actions/download-artifact@v3
        with:
          name: image-name

      - name: Deploy Docker Image
        run: |
          ORIGINAL_IMAGE_NAME=$(cat image_name.txt)
          NEW_IMAGE_NAME="petdistriacr.azurecr.io/spring-petclinic-vets-service:deploy-${{ github.run_number }}"

          echo "Original image: $ORIGINAL_IMAGE_NAME"
          echo "New image: $NEW_IMAGE_NAME"

          # Pull, retag, and push the image
          docker pull $ORIGINAL_IMAGE_NAME
          docker tag $ORIGINAL_IMAGE_NAME $NEW_IMAGE_NAME
          docker push $NEW_IMAGE_NAME
