name: Build Docker Images

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build Application with Maven
        run: |
          cd spring-petclinic-vets-service
          mvn clean package -DskipTests

      - name: Check for Dockerfile
        id: check-dockerfile
        run: |
          if [ ! -f ./spring-petclinic-vets-service/Dockerfile ]; then
            echo "No Dockerfile found in the service directory."
            exit 1
          fi

      - name: Build Docker Image
        id: docker-build
        run: |
          IMAGE_NAME="petdistriacr.azurecr.io/spring-petclinic-vets-service:pr-${{ github.event.pull_request.number }}"
          docker build -t $IMAGE_NAME ./spring-petclinic-vets-service
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Post Build Output
        run: echo "Docker image built successfully: ${{ env.IMAGE_NAME }}"
