name: Build and Push Docker Images to ACR

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout el código
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Asegura que se obtiene todo el historial para detectar cambios correctamente

      # 2. Detectar servicios modificados
      - name: Detect Modified Dockerfiles
        id: detect-changes
        run: |
          MODIFIED_SERVICES=$(git diff --name-only origin/main HEAD | grep -oE '^[^/]+/Dockerfile' | awk -F/ '{print $1}' | sort -u)
          if [ -z "$MODIFIED_SERVICES" ]; then
            echo "No modified Dockerfiles detected. Skipping build and push."
            exit 0
          fi
          echo "MODIFIED_SERVICES=$MODIFIED_SERVICES" >> $GITHUB_ENV

      # 3. Iterar sobre los servicios y construir imágenes
      - name: Build and Push Docker Images
        run: |
          for SERVICE in $MODIFIED_SERVICES; do
            echo "Detected changes in Dockerfile for service: $SERVICE"

            # Configurar variables de la imagen
            IMAGE_TAG="pr-${{ github.event.pull_request.number }}"
            IMAGE_NAME="petdistriacr.azurecr.io/$SERVICE:$IMAGE_TAG"

            # Construir y subir la imagen
            docker build -t $IMAGE_NAME ./$SERVICE
            docker push $IMAGE_NAME

            echo "Successfully processed $SERVICE with image: $IMAGE_NAME"
          done
        shell: bash

      # 4. Publicar el resultado
      - name: Output Results
        run: |
          if [ -z "$MODIFIED_SERVICES" ]; then
            echo "No Dockerfiles were modified."
          else
            echo "Docker images built and pushed for the following services: $MODIFIED_SERVICES"
          fi
